#!/usr/bin/sh

# clean lingering programs when reloaded
$HOME/.config/bspwm/clean.sh &

#Auto-Start
$HOME/.local/bin/autostart

# variable Defines
color0=#3B4252
color1=#555753

# make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

# screen
bspc monitor DisplayPort-1 -d 4 5
bspc monitor DisplayPort-2 -d 1 2 3
bspc monitor DisplayPort-3 -d 6 7

# global settings
bspc config border_width         8
bspc config window_gap           20
bspc config focused_border_color "#555753"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a microsoft-edge='^2'
bspc rule -a firefox='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


